### ISSUE TITLE
Steo29 always throws me connect timed out

### ISSUE THREAD

**Issue by radhakrishna67** [in28minutes/spring-microservices#10]
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Nov 28 22:14:16 IST 2019
There was an unexpected error (type=Internal Server Error, status=500).
connect timed out executing GET http://currency-exchange-service/currency-exchange/from/AUD/to/INR

**Comment by in28minutes** [comment]
Closing issues older than a year
