### ISSUE TITLE
Step21:Using Feign REST Client for Service Invocation

### ISSUE THREAD

**Issue by saeidehvalipour** [in28minutes/spring-microservices#12]
In SpringBoot 2.3.0 M4, When We try to AutoWired "CurrencyExchangeServiceProxy" in "CurrencyConversionController" It doesn't work:
`@Autowired
    private CurrencyExchangeServiceProxy serviceProxy;
`
"Couldn\t Autowired, No Beans of "CurrencyExchangeServiceProxy" type found. I double-check the class "CurrencyConversionBean".

Does anyone has any idea?

**Comment by in28minutes** [comment]
Please ensure you have @EnableFeignClients annotation configured with right package.
