### ISSUE TITLE
Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.util.Locale'; nested exception is java.lang.IllegalArgumentException: Locale part "en-US,en;q=0.9" contains invalid characters]

### ISSUE THREAD

**Issue by onepseudoxy** [in28minutes/spring-microservices#13]
While trying the "Step 18-International for Restful Services", I got the following error.

> [nio-8080-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.util.Locale'; nested exception is java.lang.IllegalArgumentException: Locale part "en-US,en;q=0.9" contains invalid characters]
When I try to access, via Postman' the URL: http://localhost:8080/hello-world-internationalized
WIthout specifying the "Accept-Language" and I got 400 bad Request.
I created the project using Spring Intializr while picking spring boot 2.1.15, Java, Maven Project and Dependencies like Web, DevTools, JPA and H2.

**Comment by in28minutes** [comment]
Internationalization code is now updated to use minimal configuration.
