### ISSUE TITLE
Cloning fails on Windows 10

### ISSUE THREAD

**Issue by fliegera** [in28minutes/spring-microservices#17]
Receive the following when cloning via git bash on Windows 10

`$ git clone https://github.com/in28minutes/spring-microservices.git
Cloning into 'spring-microservices'...
remote: Enumerating objects: 937, done.
remote: Total 937 (delta 0), reused 0 (delta 0), pack-reused 937
Receiving objects: 100% (937/937), 90.94 MiB | 11.81 MiB/s, done.
Resolving deltas: 100% (424/424), done.
warning: unable to access '01.framework-introductions/jpa-in-10-steps/src/main/java/com/in28minutes/learning/jpa/jpain10steps/.gitattributes': Filename too long
error: unable to create file 01.framework-introductions/jpa-in-10-steps/src/main/java/com/in28minutes/learning/jpa/jpain10steps/JpaIn10StepsApplication.java: Filename too long
error: unable to create file 01.framework-introductions/jpa-in-10-steps/src/main/java/com/in28minutes/learning/jpa/jpain10steps/UserDaoServiceCommandLineRunner.java: Filename too long
error: unable to create file 01.framework-introductions/jpa-in-10-steps/src/main/java/com/in28minutes/learning/jpa/jpain10steps/UserRepositoryCommandLineRunner.java: Filename too long
fatal: cannot create directory at '01.framework-introductions/jpa-in-10-steps/src/main/java/com/in28minutes/learning/jpa/jpain10steps/entity': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
'
`

**Comment by in28minutes** [comment]
Can you try to checkout into a folder directly in c:\?
