### ISSUE TITLE
Forbidden accessing h2 console

### ISSUE THREAD

**Issue by ravening** [in28minutes/spring-microservices#3]
In the step "Step 30 - Creating User Entity and some test data", I was successfully able to run the spring boot app but when I try to login to h2 database in http://localhost:8080/h2-console using the options you mentioned, I get a "Whitelabel Error page" indicating "Forbidden status 403" . Do you have any idea why this is happening? I cross checked the contents of your repo with mine and there is no change.

<img width="699" alt="screen shot 2018-12-13 at 15 34 24" src="https://user-images.githubusercontent.com/10645273/49945202-9f1cc580-feec-11e8-8abb-e6521c9229d6.png">

**Comment by rsr725** [comment]
Hello @in28minutes (Ranga Rao)

I'm also getting same error while using http://localhost:8080/h2-console this URL. Could you please help us.
Please check attached snip for reference.
![Spring-boot-jpa-h2-console](https://user-images.githubusercontent.com/25204144/55870629-a1471600-5ba6-11e9-8570-95abafec26e9.png)

**Comment by Saikumar544** [comment]
mvn clean install and run and disable security things
