### ISSUE TITLE
step40 & step41 fail using spring boot 2.1.2.RELEASE

### ISSUE THREAD

**Issue by antoniosanct** [in28minutes/spring-microservices#4]
"Updates to step40" don't work when upgrading Spring Boot 2.1.2.RELEASE. Spring Boot don't load AMQP dependencies and Sleuth is not sending traces to RabbitMQ default queues. Maybe Sampler declarations in projects are the cause.

Please could you give us a better solution??

Thanks a lot! Regards!

**Comment by in28minutes** [comment]
Course is now updated to 2.5.0
